# Autor: Francisco Javier Gutierrez | Unix/Linux Architect & Cloud Engineer
# files/containerd-config.toml
version = 2

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    containerd_sock = "/run/containerd/containerd.sock"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v1"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
